/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.cmgus

import org.cmgus.agenda.Agenda
import org.cmgus.libreria.Libreria

fun main() {
    // Agenda.init()
    Libreria.init()
}
